apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: drug-ai
resources:
  - namespace.yaml
  - configmap.yaml
  - redis.yaml
  - api.yaml
  - gateway.yaml
  - hpa.yaml
  - ingress.yaml
